### PR TITLE
Improve portability with /usr/bin/env

### PR DESCRIPTION
**Pull request by croaky**
http://askubuntu.com/questions/443645/starting-bash-from-usr-bin-env-or-bin

### CODE REVIEW

**Comment by croaky** [comment]
Can I get a review of this, @thoughtbot/shell? I believe @bernerdschaefer you had a Slack comment about this when it was first opened.

**Comment by mike-burns** [comment]
`/bin/sh` is a POSIX shell on everything except Solaris (up until the newest release). Since laptop only supports OS X, this change does not seem necessary.

Your SO link is for GNU Bash, for which a `/usr/bin/env` shebang is the correct thing to do since it is incredibly non-portable.

**Comment by croaky** [comment]
Thanks, @mike-burns. Via manual testing, the before and after options both work on OS X.

The Laptop script over the years has gone back and forth on Linux support depending on who at thoughtbot is willing to help support it. Part of me was thinking to prefer the portability in case we return to that, or to better support forkers who want to make it run on Linux.

Moreso, though, I just want this script to represent any shell best practices so I can refer to it later as an example when writing other scripts.

Think I should close without merging or merge it due to those reasons, with the understanding it isn't strictly necessary?

**Comment by jferris** [comment]
> Moreso, though, I just want this script to represent any shell best practices so I can refer to it later as an example when writing other scripts.

I like this idea.

> Your SO link is for GNU Bash, for which a /usr/bin/env shebang is the correct thing to do since it is incredibly non-portable.

It sounds like you're saying `/usr/bin/env sh` would be less portable?

> Think I should close without merging or merge it due to those reasons, with the understanding it isn't strictly necessary?

I think `/bin/sh` is a fairly portable assumption, and it seems to work on OS X, so I think closing without merging makes the most sense.

**Comment by mike-burns** [comment]
Yes, close without merging. `/bin/sh` is portable to all unices except old Solaris -- and to support them we'd need to re-evaluate a few other things, too.

**Comment by croaky** [comment]
Sounds good, thanks for the info.

**Pull request closed without merging**
