### PR TITLE
added brew cask functionality

### PR DESCRIPTION
**Pull request by autodidacticon**
Added brew cask. 

Added iterm2 as an example. Can remove if desired.

### CODE REVIEW

**Comment by Keithbsmiley** [comment]
Just my 2 cents, not really a big deal but I still have [issues](https://github.com/caskroom/homebrew-cask/issues/3888) with cask.

**Comment by autodidacticon** [comment]
wrt caskroom/homebrew-cask#2534, shall I append this to the zshrc?
`export HOMEBREW_CASK_OPTS="--appdir=/Applications"`

**Comment by Keithbsmiley** [comment]
Yep you can definitely set that. I'm definitely deferring this to others, cask just isn't for me.

**Comment by autodidacticon** [comment]
Updated script to append to zshrc to set brew cask opts

**Comment by croaky** [comment]
The current script doesn't require cask for any packages, does it?

We have https://github.com/thoughtbot/laptop/wiki, which is similar to this pull request, but we don't do a good job linking to it from the "Customize" section of the README.

What if instead of merging this into the codebase, you make any improvements to that wiki page, and then make this pull request just a doc change, adding a link to the wiki from the "Customize" section of the README?

**Comment by autodidacticon** [comment]
`Put your personal customizations in ~/.laptop.local`
Duh.

It seems this is already accounted for in the wiki. Thanks for the feedback. Amended PR as per comments.

**Comment by croaky** [comment]
@autodidacticon Awesome, thanks. Merged as b153d5e.

**Pull request closed without merging**
