### PR TITLE
Modify README to make script execution commands clearer

### PR DESCRIPTION
**Pull request by Charliemowood**
It is not overly clear that the commands need to run separately or where they should be run. This minor modification hopefully makes it more clear.

### CODE REVIEW

**Comment by gohanlon** [comment]
I can see how someone could mistakenly attempt to run all three of these commands at once — good catch!

Knowing that each of these commands need to be run individually requires familiarity with `curl`, `less` and `sh`. There‘s a more important implication, though: that users may attempt to install Laptop without first reading the install script.

Laptop‘s install could easily be a single command, and, in fact it [used to be](https://github.com/thoughtbot/laptop/commit/85386c09ffeae0ae60fa3b9dd74947a5dfd888cb). Instead, Laptop encourages a super-important practice: reading and understanding scripts before running them. Maybe the README should do more to encourage this?

I like @Charliemowood‘s  proposed change, but, in addition, I‘d favor reworking the "download, review, then execute" annotation to encourage the best practice even more strongly:

# Install

Download the script:

``` sh
curl --remote-name https://raw.githubusercontent.com/thoughtbot/laptop/master/mac
```

Review the script (never run a script you haven‘t read!):

``` sh
less mac
```

Execute the downloaded script:

``` sh
sh mac 2>&1 | tee ~/laptop.log
```

**Comment by Charliemowood** [comment]
@gohanlon I really like the changes you have made and having a clear warning. I would support your improved version with a warning and really explaining what each command does. I think having a review step makes a lot of sense and a single command would not be a good result for the users as it would encourage them to run the script without thinking about it. 

There is the option of some nice markdown with a clearer warning. Something like:

**Note:**
> It is very important that you read through every script that you run on your operation system. Scripts can make make major changes that you did not intend. Please review this script carefully before running this script on your system.

It might also be nicer to really explain what is meant by `curl`, `less` and breaking down what the `sh mac 2>&1 | tee ~/laptop.log` for users who are not so Bash savvy. I will reflect on it and add a slightly more detailed explanations while hopefully not overly cluttering the README.

**Comment by Charliemowood** [comment]
Based @gohanlon suggestions I have expanded the installation instructions hopefully now the installation instructions are more explicit and clear to user as well as encouraging a more thorough review of the script. 

Here is a preview of the amended README.
https://github.com/Charliemowood/laptop/tree/patch-1

**Comment by croaky** [comment]
Thanks, @Charliemowood and @gohanlon! I've rebased and merged as 4dcfacf.

It uses a version of these instructions that split up the steps into three as suggested, adds the "why" statement of the `less` review step, but keeps the overall instructions short.

**Comment by croaky** [comment]
I also added an optional step to review the log.

**Pull request closed without merging**
