### PR TITLE
Generate an SSH key if one doesn't exist

### PR DESCRIPTION
**Pull request by croaky**
https://github.com/thoughtbot/laptop/issues/360

### CODE REVIEW

**Comment by croaky** [comment]
@pbrisbin On #360 you commented:

> If the question is, "should laptop use the ssh-keygen command suggested in that post", then yes, of course. 

Does that mean you're in favor of laptop running `ssh-keygen` (but maybe not opening the browser, etc)? @calebthompson mentioned in #360 that the more secure SSH options prevented him from hosting tmate sessions, so this PR is nice and basic.

**Comment by calebthompson** [comment]
Don't get me wrong. I still use the more secure settings. I just don't host tmate sessions anymore, or when I do I do so with a weaker, throwaway key.

**Comment by pbrisbin** [comment]
> Does that mean you're in favor of laptop running ssh-keygen (but maybe not opening the browser, etc)?

I have a fuzzy memory of my thinking at the time. Re-reading my comment, I *think* what I meant was:

I'm not in favor of laptop doing this for the user. However, if you do decide to do it, the command suggested in that post is a good one.

**Comment by croaky** [comment]
Closing without merging. Nice to have, not a need.

**Pull request closed without merging**
