### PR TITLE
Remove gpg-suite Mail.app plugin

### LINKED ISSUE #531: Remove gpg-suite
Hey friends, researchers have found a vulnerability that prompted EFF to make this recommendation:

> Our advice, which mirrors that of the researchers, is to immediately disable and/or uninstall tools that automatically decrypt PGP-encrypted email. Until the flaws described in the paper are more widely understood and fixed, users should arrange for the use of alternative end-to-end secure channels, such as Signal, and temporarily stop sending and especially reading PGP-encrypted email.

https://www.eff.org/deeplinks/2018/05/attention-pgp-users-new-vulnerabilities-require-you-take-action-now

The laptop script includes gpg-suite. From what I can tell, gpg-suite autodecrypts emails by default.

### PR DESCRIPTION
**Pull request by ckundo**
- The plugin autodecrypts messages, which exposes users to EFAIL vulnerability.
- https://efail.de/
- https://www.eff.org/deeplinks/2018/05/attention-pgp-users-new-vulnerabilities-require-you-take-action-now

[Closes #531]

### CODE REVIEW

**Comment by derekprior** [comment]
This would break the asdf install of nodejs which attempts to verify the package signatures. We can disable this check when installing nodejs, but then any future installs of nodejs would need to know to do this.

Another alternative would be to `rm /Library/Mail/Bundles/GPGMail.mailbundle`

**Comment by ckundo** [comment]
@derekprior from what I can tell, the asdf node installation uses `gpg` cli, which doesn't require the entire `gpg-suite` installation. I think just `brew install gpg2` would work.

**Comment by georgebrock** [comment]
If I've understood the vulnerabilities correctly, they require the message to not only be decrypted but also rendered in a mail agent that downloads images, styles, etc. by default.

Seems like Derek's proposed solution (`rm …/GPGMail.mailbundle`) would mitigate that, without needing to remove the whole of the GPG suite.

See https://efail.de/ for more.

**Comment by cpytel** [comment]
This PR was made against master, so I needed to recreate it. I also wanted to test it on a fresh install of macOS Monterey. While searching, I found an alternative brew package which does not install the mail extension and I opened a PR for that instead https://github.com/thoughtbot/laptop/pull/607

**Comment by ckundo** [comment]
thanks @cpytel sounds good!

**Pull request closed without merging**
