### PR TITLE
Remove rbenv-gem-rehash plugin installation

### PR DESCRIPTION
**Pull request by keith**
This plugin was merged into rbenv
https://github.com/sstephenson/rbenv/pull/638

### CODE REVIEW

**Comment by allaire** [comment]
This is problematic, since it was merged into rbenv, but currently laptop installs brew version, which is 0.4.0 (from 2014) https://github.com/sstephenson/rbenv/releases/tag/v0.4.0 and this version does not have rbenv-gem-rehash merged. I did this investigation because my gems were not rehashing. Ran `brew install rbenv-gem-rehash` fixed it for me!

cc @croaky

**Comment by Keithbsmiley** [comment]
Ugh. To solve this at the moment we would either have to installed the mentioned plugin, or build rbenv from `--HEAD`

**Comment by croaky** [comment]
@Keithbsmiley It seems like we should go with the `--HEAD` approach? rbenv 0.4.0 is two years old. I'm struggling a little bit with how to pass that `--HEAD` flag through to our functions correctly.

**Comment by gohanlon** [comment]
@croaky I don't see a great solution within Laptop, and of course there's a straightforward solution at the upstream — rbenv tags stable versions and revs their Homebrew formula accordingly.

### My Recommendation

If rbenv isn't going to mark stable releases, it shouldn't be in Homebrew. Homebrew maintainers often remove formulas that stop marking stable releases — marking stable releases is one of the stated criteria for being accepted as a Homebrew Formula in the first place. Maintainers move these formulas to the `homebrew/head-only` repo: https://github.com/Homebrew/homebrew-head-only.

Assuming rbenv doesn't start making stable releases, I think Laptop should stop using Homebrew for rbenv. Laptop should probably `brew uninstall` it (if it's installed) and then clone it directly as described by rbenv's README:

> `git clone https://github.com/sstephenson/rbenv.git ~/.rbenv`

If the repo exists, Laptop can `git pull` to get the latest (also from rbenv's README).

### Feasible Alternative

However, if Laptop wants to stick with Homebrew for rbenv, I think it'd make sense for installing/upgrading `--HEAD` formulas to be it's own function: `brew_install_or_reinstall_head`. The `brew_install_or_upgrade` function already has a fair amount of complexity, and `--HEAD` formulas don't work like other Homebrew formula — they're kinda kludgey, actually.

There's no Homebrew-way to know that an installed `--HEAD` formula is outdated. So, if it's not installed, you install it. If it's already installed, you must assume it needs to be reinstalled (even if the formulas `HEAD` hasn't actually changed). See https://github.com/Homebrew/homebrew/issues/13197, opened in 2012 and still open.

Something like this:

``` bash
brew_install_or_reinstall_head() {
  if brew_is_installed "$1"; then
    fancy_echo "Reinstalling %s from HEAD ..." "$1"
    brew reinstall --HEAD "$@"
  else
    fancy_echo "Installing %s from HEAD ..." "$1"
    brew install --HEAD "$@"
  fi
}
```

**Pull request merged**
