### PR TITLE
Remove NVM, simplify to `brew install node`

### PR DESCRIPTION
**Pull request by croaky**
From @derekprior:

> I never used NVM. I just kept my homebrew installed version pinned to
> the version we were using. As a company this is probably totally fine
> because we don't jump back and forth between node projects like we do
> with Ruby projects. Also, there is no "system" node to worry about.

https://github.com/thoughtbot/laptop/pull/341#issuecomment-66179326

### CODE REVIEW

**Comment by Keithbsmiley** [comment]
:+1:

**Comment by allaire** [comment]
@croaky I don't mind about the removal of NVM, but why keep rbenv and remove NVM? Don't they serve the same purpose?

**Comment by derekprior** [comment]
I think the commit explains this pretty well.

**Comment by allaire** [comment]
Business decision, I see.. Alright!

**Pull request merged**
