### PR TITLE
Wrap entire script in `brew upgrade; brew cleanup` and remove custom Homebrew functions

### PR DESCRIPTION
**Pull request by croaky**
This is just an idea I'm playing with.
It changes the behavior of the Laptop script somewhat significantly.
What do you think: is this a good idea or bad idea?

Before:

* Update all Homebrew formulas.
* Install or upgrade each Laptop-specific Homebrew formula.

After:

* Update all Homebrew formulas.
* Upgrade all Homebrew formulas on the machine,
  including formulas not controlled by Laptop.
* Try to install Laptop-specific Homebrew formulas.
  Homebrew prints "Warning: formula-X.Y.Z already installed" for
  formulas that are already using the latest.
* Deprecate old formulas.

The custom functions are therefore no longer necessary.
We can use "vanilla" Homebrew commands in their place.

### CODE REVIEW

**Comment by croaky** [comment]
I'm feeling good about this after further thought. @gabebw @jferris @geoffharcourt any opinions?

**Comment by geoffharcourt** [comment]
I think this is probably horrifying to our comrades who carefully inspect software before they install, but I use `brew update && brew upgrade` pretty liberally, in part because I'm a little cautious about what packages I'll install from Homebrew at all.

_Most_ of the software we've elected to install with Laptop is probably safe to always upgrade to the latest available version (things like Vim, tmux, etc.). However, some of the Laptop-installed packages like PG can be pretty temperamental on upgrade (PG sometimes requires a DB migration, I've had to dump and re-import databases after minor version updates, etc.). I think a user re-running Laptop is expecting to upgrade their installed software, so this probably isn't a bad thing, but it's worth considering.

I would be OK running this on my machine, and I think it's not a significant change for anyone setting up a machine from scratch. I expect that the population of people running this on a pre-set-up machine and the population who would be OK with a blanket upgrade have a significant overlap, but I'm curious what the other folks CCed here think.

**Comment by gabebw** [comment]
I agree with Geoff in every respect: I personally think this is fine (I run `brew update && brew upgrade` periodically), but the people who don't like this will probably _really_ not like this.

Even I, a `brew upgrade` fan, do have packages I don't want upgraded (postgresql and tmux). I `brew pin` packages I don't want upgraded so I wouldn't be affected, but for people caught by surprise, it would be very difficult (impossible?) to downgrade.

Which is all to say: I am :-1: on this because I think this makes laptop overstep its perceived responsibilities.

**Comment by croaky** [comment]
Okay, thanks for the feedback. Closing without merging. Extracted the non-/less-controversial changes I came across while working on this to https://github.com/thoughtbot/laptop/pull/432 and https://github.com/thoughtbot/laptop/pull/433

**Pull request closed without merging**
