### PR TITLE
Provide Docker as an example customization

### PR DESCRIPTION
**Pull request by croaky**
Docker isn't in common enough use at thoughtbot to
make this part of the script yet
but documenting it can encourage its use.

https://github.com/thoughtbot/laptop/pull/411#issuecomment-168594168

### CODE REVIEW

**Comment by ktheory** [comment]
Docker Toolbox comes with a quickstart script to create the default VM if need by and ensure it's running. You may want to use that instead of some custom shell functions.

Check out:

```
'/Applications/Docker/Docker Quickstart Terminal.app/Contents/Resources/Scripts/start.sh'
```

That's from the default Docker Toolbox pkg install; path may be different for the cask.

**Comment by AlJohri** [comment]
Shouldn't you add `eval $(docker-machine env default)` to your zsh profile?

**Comment by AlJohri** [comment]
Oh oops, you already talked about that in https://github.com/thoughtbot/laptop/pull/411

**Comment by croaky** [comment]
Thanks, @ktheory; it would be great to use the Quickstart instead of maintaining custom code. I haven't been able to figure out the path for it so I'm going to merge this as-is. If someone else is able to figure out the path, I'm happy to come back to it and clean it up.

**Pull request merged**
